config/routes.rb
Rails.application.routes.draw do
  
  
  

  namespace :admin do
    resources :users
  	resources :papers    
    resources :questions 
  end

  resources :papers do 
  	member do 
  		get :participate
  		patch :answer
      get :result 
  	end
  end

  

  devise_for :users
  root "home#index"

  namespace :api do 
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      
      resources :papers do 
        member do 
          get :participate
          patch :answer
          get :result 
        end
      end
      resources :users do 
        collection{get :top}
      end

      resources :admin_papers

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
	validates_presence_of  :body
end

app/models/paper.rb
class Paper < ApplicationRecord
	has_and_belongs_to_many :questions	
	has_many :paper_attempts
	before_create :set_number_


	def to_param
		set_number
	end

	def set_number_
		self.set_number = "LPU" + SecureRandom.random_number(10**9).to_s(10).rjust(9, '0').upcase
	end

	def top_10_user
		paper_attempts.order("final_score desc").limit(10)
	end


	
end

app/models/paper_attempt.rb
class PaperAttempt < ApplicationRecord
	belongs_to :paper
	belongs_to :user
	has_many :paper_attempt_answers, dependent: :destroy
	has_many :options, through: :paper_attempt_answers 


	accepts_nested_attributes_for :paper_attempt_answers

	def self.over_all_10
		self.order("final_score desc").limit(10)
	end

	def check_score
		correct_ans = self.options.select{|a| a.is_correct == true}.count
		wrong_ans = self.options.select{|a| a.is_correct == false}.count
		f_s = 0
		f_s = (correct_ans * 10) + (wrong_ans * (-5))
		f_s
		self.final_score = f_s
		self.save
	end
end

app/models/paper_attempt_answer.rb
class PaperAttemptAnswer < ApplicationRecord
	belongs_to :option
	belongs_to :paper_attempt
end

app/models/papers_question.rb
class PapersQuestion < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :options, dependent: :destroy
	enum question_type: %i{scq mcq}

	validates_presence_of :body, :question_type

	accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :paper_attempts
  def admin?
  	self.role == "admin"
	end       

	def create_and_get_api_key
		self.token = Digest::SHA1.hexdigest "#{Time.now.to_i}#{1}"
		self.save
		return self.token
	end
end

app/controllers/api/papers_controller.rb
module Api
		class PapersController < Api::ApplicationController
			before_action :set_paper, only: [:participate]
			def index
				@papers = Paper.all
				render json: {
					success: true,
					papers: @papers.as_json
				}
			end


			def participate
				if current_user.paper_attempts.collect(&:paper_id).include?(@paper.id)
					render json: {
						success: false,
						message: "You have already attempted this quiz."	
					}
				else
					@attempt = current_user.paper_attempts.new(paper_id: @paper.id)
					if @attempt.save
						render json: {
							success: true,
							questions: @paper.as_json(include: { questions: {
                           include:  [:options ]
                         } })
						}
					else
						render json: {
							success: false,
							message: "#{attempt.errors.full_messages.join(',')}"
						}
					end
				end
			end


			private
					def paper_attempt_params
						params.require(:paper_attempt).permit(paper_attempt_answers_attributes: [:option_id])	
					end

					def set_paper
							@paper = Paper.find_by(set_number: params[:id])
					end					

					
		end
end

app/controllers/api/users_controller.rb
module Api
		class UsersController < Api::ApplicationController
			before_action :check_admin_user!

			def index
				 @users = User.all - User.where(role: "admin")

				 render json: {
				 	success: true,
				 	users: @users.as_json
				 }
			end

			def top
				@all_attempts = PaperAttempt.over_all_10
				 render json: {
				 	success: true,
				 	attempts: @all_attempts.as_json(
				 		include: :user
				 		)
				 }
			end
			
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def check_admin?
  	if current_user && current_user.admin?
  	else
  		flash[:error] = "You are not authorized"
  		redirect_to root_url
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@papers = Paper.all
	end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
	before_action :authenticate_user!

	before_action :set_paper 


	def participate
		if current_user.paper_attempts.collect(&:paper_id).include?(@paper.id)
			flash[:warning] = "You have already attempted this quiz."
			redirect_to root_url
		else
			@attempt = current_user.paper_attempts.new(paper_id: @paper.id)
			if @attempt.save
				flash[:warning] = "You have stated this quiz do not reload or leave it without complete."
			else
				flash[:error] = "#{attempt.errors.full_messages.join(',')}"
				redirect_to root_url
			end
		end
	end


	def answer
		@paper_attempt = current_user.paper_attempts.find_by(id: params[:paper_attempt_id])
		if @paper_attempt.update(paper_attempt_params)
			@paper_attempt.check_score
			flash[:success] = "Your quiz is submitted"
			redirect_to root_url
		else
			flash[:error] = "#{@paper_attempt.errors.full_messages.join(',')}"
			redirect_to root_url
		end
	end

	def result
		@paper_attempt = current_user.paper_attempts.find_by(paper_id: @paper.id)
		if @paper_attempt.blank?
			flash[:error] = "You have not attempted this quiz."
			redirect_to root_url
		end
	end

	private
		def paper_attempt_params
			params.require(:paper_attempt).permit(paper_attempt_answers_attributes: [:option_id])	
		end

		def set_paper
				@paper = Paper.find_by(set_number: params[:id])
		end
end

app/helpers/admin/papers_helper.rb
module Admin::PapersHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/sessions_helper.rb
module Api::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LpuTest</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

		<!-- Popper JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash_messages"><%= flash_messages(:close)%></div>
  	<%= render partial:"shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
      </li>
      <%-if current_user%>
        <%-if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" href="<%=admin_papers_path%>">Papers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=admin_questions_path%>">Questions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=admin_users_path%>">Users</a>
          </li>
        <%-end%>  
      <%-else%>
        <li class="nav-item">
          <a class="nav-link " href="/users/sign_in">Login</a>
        </li>
      <%-end%>  
    </ul>
  </div>
</nav>