config/routes.rb
Rails.application.routes.draw do
  
  
  

  namespace :admin do
    resources :users
  	resources :papers    
    resources :questions 
  end

  resources :papers do 
  	member do 
  		get :participate
  		patch :answer
      get :result 
  	end
  end

  

  devise_for :users
  root "home#index"

  namespace :api do 
      resources :sessions, only: [:create, :destroy]
      resources :registrations, only: [:create]
      
      resources :papers do 
        member do 
          get :participate
          patch :answer
          get :result 
        end
      end
      resources :users do 
        collection{get :top}
      end

      resources :admin_papers

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :options, dependent: :destroy
	enum question_type: %i{scq mcq}

	validates_presence_of :body, :question_type

	accepts_nested_attributes_for :options, allow_destroy: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :check_admin?
  before_action :set_question, only: [:edit, :update, :destroy, :show]	

  def index
  	@questions = Question.all
  end

  def new
  	@question = Question.new
  end

  

  def destroy
  	if @question.destroy
  		flash[:success] = "Question has been removed"	
  		redirect_to admin_questions_path
  	else
  		flash[:error] = "#{@question.errors.full_messages.join(',')}"	
  		redirect_to admin_questions_path
  	end
  end

  def create
  	@question = Question.new(question_param)
  	if @question.save
  		flash[:success] = "Question has been created"	
  		redirect_to admin_questions_path
  	else
  		flash[:error] = "#{@question.errors.full_messages.join(',')}"	
  		render(:new)
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @question.update(question_param)
  		flash[:success] = "Question has been updated"	
  		redirect_to admin_questions_path
  	else
  		flash[:error] = "#{@question.errors.full_messages.join(',')}"	
  		render(:edit)
  	end
  end

  private
  	def set_question
  		@question = Question.find_by(id: params[:id])	
  	end

	  def question_param
	  	params.require(:question).permit(:body, :question_type, options_attributes: [:id, :body, :is_correct])
	  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/views/admin/questions/_form.html.slim
.form-group	
	=f.label :question_text
	=f.text_area :body, 	class:"form-control", required: true
.form-group	
	=f.label :type_of_question
	=f.select :question_type, options_for_select(Question.question_types.keys, selected: @question.question_type),{prompt: "select"}, {class:"form-control", required: true}

hr
h5 Option set

app/views/admin/questions/_option.html.slim
-if option.persisted?
	=hidden_field_tag "question[options_attributes][][id]", option.id
.row
	.col-md-9
		=text_area_tag "question[options_attributes][][body]", option.try(:body), class:"form-control", placeholder: "Option text here"
	.col-md-3
		label
			|Click if correct 
			=check_box_tag "question[options_attributes][][is_correct]", true, option.is_correct
br

app/views/admin/questions/add_options.js.erb
$("#option-rows").append("<%= escape_javascript render('option')%>")

app/views/admin/questions/edit.html.slim
.col-md-8.offset-md-2
	.panel.panel-default
		.panel-heading
			|Create new question
		.panel-body
			=form_for [:admin, @question] do |f|
				=render "form", f:f
				-if @question.options.present?
					-@question.options.each do |option|
						=render "option", option:option
				=f.submit "Update question"
					

app/views/admin/questions/index.html.slim
=link_to "create new", new_admin_question_path, class:"btn btn-primary"

.col-md-12
	-if @questions.present?
		table.table
			thead
				tr
					th scope="col"  #
					th scope="col"  Body
					th scope="col"  Number of options
					th scope="col"  Type
			tbody
				-@questions.each do |question|
					tr
						th scope="row"  
						td =truncate question.body, length: 20
						td =question.options.try(:count)
						td =question.question_type 
						td 
							=link_to "remove", admin_question_path(question), method: :delete, class:"btn btn-danger"
							=link_to "edit", edit_admin_question_path(question), class:"btn btn-success"
					

app/views/admin/questions/new.html.slim
.col-md-8.offset-md-2
	.panel.panel-default
		.panel-heading
			|Create new question
		.panel-body
			=form_for [:admin, @question] do |f|
				=render "form", f:f
				-(0..3).each do |i|
					=render "option", option: Option.new
				=f.submit "Create question"
					

app/views/admin/questions/show.html.slim
h1 Admin::Questions#show
p Find me in app/views/admin/questions/show.html.slim